name: go integration tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  integration:
    runs-on: ubuntu-latest
    container: golang:1.21

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_gophermart
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Integration Test
        run: |
          go test \
            -v \
            -tags=integration \
            github.com/k-orolevsk-y/gophermart/internal/gophermart/repository \
            -d="postgresql://postgres:postgres@postgres/test_gophermart?sslmode=disable"
